# Generated by Django 6.0.4 on 2026-05-04 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_name_1', models.CharField(max_length=50)),
                ('player_name_2', models.CharField(blank=True, max_length=50, null=True)),
                ('player_mode', models.CharField(choices=[('1p', 'Single Player'), ('2p', 'Two Players')], max_length=2)),
                ('source_mode', models.CharField(choices=[('camera', 'Face Record'), ('form', 'System Images')], default='camera', max_length=10)),
                ('total_rounds', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=2)),
                ('best_time', models.FloatField()),
                ('rounds_won', models.IntegerField(default=0)),
                ('total_rounds', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['best_time'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('grid_size', models.IntegerField(default=5)),
                ('time_p1', models.FloatField(blank=True, null=True)),
                ('time_p2', models.FloatField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=10, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='facepuzzle.gamesession')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('session', 'round_number')},
            },
        ),
    ]
